const cities = [
  "Herat",
  "Kabul",
  "Kandahar",
  "Molah",
  "Rana",
  "Shar",
  "Sharif",
  "Wazir Akbar Khan",
  "Elbasan",
  "Petran",
  "Pogradec",
  "Shkoder",
  "Tirana",
  "Ura Vajgurore",
  "Algiers",
  "Annaba",
  "Azazga",
  "Batna City",
  "Blida",
  "Bordj",
  "Bordj Bou Arreridj",
  "Bougara",
  "Cheraga",
  "Chlef",
  "Constantine",
  "Djelfa",
  "Draria",
  "El Tarf",
  "Hussein Dey",
  "Illizi",
  "Jijel",
  "Kouba",
  "Laghouat",
  "Oran",
  "Ouargla",
  "Oued Smar",
  "Relizane",
  "Rouiba",
  "Saida",
  "Souk Ahras",
  "Tamanghasset",
  "Tiaret",
  "Tissemsilt",
  "Tizi",
  "Tizi Ouzou",
  "Tlemcen",
  "Andorra la Vella",
  "Canillo",
  "Encamp",
  "Engordany",
  "Escaldes-Engordany",
  "La Massana",
  "Llorts",
  "Ordino",
  "Santa Coloma",
  "Sispony",
  "Soldeu",
  "Ambriz",
  "Benguela",
  "Cabinda",
  "Cacole",
  "Camabatela",
  "Cazeta",
  "Huambo",
  "Kuito",
  "Lobito",
  "Luanda",
  "Lubango",
  "Lucapa",
  "Lumeje",
  "Malanje",
  "Menongue",
  "Muxaluando",
  "Namibe",
  "Ondjiva",
  "Piri",
  "Saurimo",
  "Talatona",
  "All Saints",
  "Cassada Gardens",
  "Codrington",
  "Old Road",
  "Parham",
  "Woods"
      "28 de Noviembre",
  "Abasto",
  "Acassuso",
  "Acebal",
  "Acevedo",
  "Adelia Maria",
  "Agua de Oro",
  "Albardon",
  "Albarellos",
  "Alberdi",
  "Alberti",
  "Aldo Bonzi",
  "Alejandro Korn",
  "Alicia",
  "Allen",
  "Almafuerte",
  "Almagro",
  "Almirante Brown",
  "Alta Gracia",
  "Alta Italia",
  "Alvarez",
  "Alvear",
  "Anatuya",
  "Angelica",
  "Antonio Carboni",
  "Apostoles",
  "Arequito",
  "Armstrong",
  "Arrecifes",
  "Arroyito",
  "Arroyito",
  "Arroyito Challaco",
  "Arroyo Seco",
  "Arteaga",
  "Asamblea",
  "Ascension",
  "Avellaneda",
  "Avellaneda",
  "Ayacucho",
  "Azara",
  "Azul",
  "Balcarce",
  "Balnearia",
  "Banda del Rio Sali",
  "Bandera",
  "Banfield",
  "Baradero",
  "Bariloche",
  "Barrio Fisherton",
  "Batan",
  "Beccar",
  "Belen de Escobar",
  "Belgrano",
  "Belgrano",
  "Bell Ville",
  "Bella Vista",
  "Bella Vista",
  "Benavidez",
  "Berazategui",
  "Berisso",
  "Bernal",
  "Bernardo Larroude",
  "Bernasconi",
  "Bigand",
  "Bombal",
  "Bordenave",
  "Bosch",
  "Bosques",
  "Boulogne",
  "Bovril",
  "Bragado",
  "Brandsen",
  "Brinkmann",
  "Buenos Aires",
  "Burzaco",
  "Bustinza",
  "Caballito",
  "Calderon",
  "Caleta Olivia",
  "Caleufu",
  "Camilo Aldao",
  "Campana",
  "Canada de Gomez",
  "Canada del Ucle",
  "Canada Rosquin",
  "Canals",
  "Canning",
  "Canuelas",
  "Capilla del Monte",
  "Capilla del Senor",
  "Capitan Bermudez",
  "Carhue",
  "Carlos Casares",
  "Carlos Pellegrini",
  "Carlos Tejedor",
  "Caseros",
  "Casilda",
  "Castelar",
  "Castelli",
  "Castillo",
  "Catriel",
  "Catrilo",
  "Cavanagh",
  "Centenario",
  "Ceres",
  "Cervantes",
  "Chacabuco",
  "Chacarita",
  "Chajari",
  "Charata",
  "Chateaubriand",
  "Chilecito",
  "Chivilcoy",
  "Choele Choel",
  "Chorroarin",
  "Cinco Saltos",
  "Cipolletti",
  "City Bell",
  "Ciudad General Belgrano",
  "Ciudadela",
  "Claypole",
  "Clorinda",
  "Colon",
  "Colon",
  "Colonia Baron",
  "Colonia Caroya",
  "Colonia San Miguel Arcangel",
  "Comodoro Rivadavia",
  "Concepcion",
  "Concepcion",
  "Concordia",
  "Constituyentes",
  "Coronel Dorrego",
  "Coronel Martinez de Hoz",
  "Coronel Pringles",
  "Corral de Bustos",
  "Corralitos",
  "Corrientes",
  "Cosquin",
  "Coy Aike",
  "Cramer",
  "Crespo",
  "Cruz del Eje",
  "Curuzu Cuatia",
  "Cutral-Co",
  "Darregueira",
  "De Mayo",
  "Del Campillo",
  "Del Viso",
  "Despenaderos",
  "Devoto",
  "Diaz",
  "Diego de Alvear",
  "Doblas",
  "Dock Sud",
  "Dolores",
  "Don Bosco",
  "Don Torcuato",
  "Drabble",
  "Eduardo Castex",
  "El Calafate",
  "El Dorado",
  "El Hoyo",
  "El Palomar",
  "El Palomar",
  "El Talar",
  "El Trebol",
  "Eldorado",
  "Embalse",
  "Empalme Lobos",
  "Ensenada",
  "Esperanza",
  "Esquel",
  "Esteban Echeverria",
  "Ezeiza",
  "Ezpeleta",
  "Famailla",
  "Fatima",
  "Federal",
  "Fernandez",
  "Firmat",
  "Florencio Varela",
  "Florentino Ameghino",
  "Flores",
  "Floresta",
  "Florida",
  "Formosa",
  "Francisco Alvarez",
  "Franck",
  "Fray Luis A. Beltran",
  "Freyre",
  "Frias",
  "Funes",
  "Gaiman",
  "Galvez",
  "Garin",
  "Garupa",
  "General Acha",
  "General Alvear",
  "General Cabrera",
  "General Deheza",
  "General Guido",
  "General Juan Madariaga",
  "General Lagos",
  "General Las Heras",
  "General Lavalle",
  "General Mansilla",
  "General Martin Miguel de Guemes",
  "General Pacheco",
  "General Paz",
  "General Pico",
  "General Roca",
  "General Roca",
  "General Rodriguez",
  "General San Martin",
  "General San Martin",
  "General Viamonte",
  "General Villegas",
  "Germania",
  "Glew",
  "Gobernador Crespo",
  "Gobernador Galvez",
  "Godoy",
  "Godoy Cruz",
  "Gonzalez Catan",
  "Gonzalez Moreno",
  "Goya",
  "Granadero Baigorria",
  "Grand Bourg",
  "Gualeguay",
  "Guatrache",
  "Guernica",
  "Henderson",
  "Hernando",
  "Hersilia",
  "Hilario",
  "Hilario Ascasubi",
  "Hipatia",
  "Hipolito Yrigoyen",
  "Huanchillas",
  "Huanguelen",
  "Huinca Renanco",
  "Humahuaca",
  "Hurlingham",
  "Ibarlucea",
  "Ibicuy",
  "Independencia",
  "Ingeniero Beaugey",
  "Ingeniero Luiggi",
  "Ingeniero Maschwitz",
  "Intendente Alvear",
  "Isidro Casanova",
  "Ituzaingo",
  "James Craik",
  "Jauregui",
  "Jeppener",
  "Jesus Maria",
  "Jose Leon Suarez",
  "Jose Marmol",
  "Juan Pujol",
  "Justiniano Posse",
  "La Banda",
  "La Boca",
  "La Calera",
  "La Cumbre",
  "La Falda",
  "La Leonesa",
  "La Lucila",
  "La Madrid",
  "La Pampa",
  "La Para",
  "La Paz",
  "La Paz",
  "La Plata",
  "La Punta",
  "La Rioja",
  "La Tablada",
  "La Union",
  "La Violeta",
  "Laborde",
  "Laboulaye",
  "Laferrere",
  "Laguna Alsina",
  "Lanus",
  "Larroque",
  "Las Catitas",
  "Las Flores",
  "Las Flores",
  "Las Heras",
  "Las Perdices",
  "Las Rosas",
  "Las Talitas",
  "Las Varillas",
  "Lavalle",
  "Leandro N. Alem",
  "Leones",
  "Libertad",
  "Lima",
  "Liniers",
  "Llavallol",
  "Lobos",
  "Lomas de Zamora",
  "Lomas del Mirador",
  "Longchamps",
  "Los Antiguos",
  "Los Cardales",
  "Los Molinos",
  "Los Polvorines",
  "Luis Guillon",
  "Lujan de Cuyo",
  "Luque",
  "Luzuriaga",
  "Lynch",
  "Macachin",
  "Magdalena",
  "Magdalena",
  "Maggiolo",
  "Maipu",
  "Maipu",
  "Manantial",
  "Manfredi",
  "Manuel J. Cobo",
  "Maquinista Savio",
  "Mar de Ajo",
  "Mar del Plata",
  "Mar del Tuyu",
  "Marcos Juarez",
  "Marcos Paz",
  "Margarita",
  "Maria Ignacia",
  "Maria Juana",
  "Mariano Acosta",
  "Mariano J. Haedo",
  "Mariano Moreno",
  "Martinez",
  "Matheu",
  "Mayor Buratovich",
  "Melincue",
  "Mendiolaza",
  "Mendoza",
  "Mercedes",
  "Mercedes",
  "Merlo",
  "Merlo",
  "Minacar",
  "Miramar",
  "Miramar",
  "Monje",
  "Monte Hermoso",
  "Monteros",
  "Montserrat",
  "Moreno",
  "Moron",
  "Morteros",
  "Muniz",
  "Munro",
  "Navarro",
  "Navarro",
  "Necochea",
  "Nogoya",
  "Nordelta",
  "Nunez",
  "Obera",
  "Oliva",
  "Oliveros",
  "Olivos",
  "Oncativo",
  "Open Door",
  "Ordonez",
  "Palermo",
  "Palmira",
  "Palpala",
  "Partido de Jose C. Paz",
  "Pasco",
  "Paso del Rey",
  "Paternal",
  "Pavon",
  "Pedernales",
  "Pedro Luro",
  "Pellegrini",
  "Perez",
  "Pergamino",
  "Perico",
  "Perito Moreno",
  "Piamonte",
  "Pico de Salamanca",
  "Pico Truncado",
  "Pigue",
  "Pilar",
  "Pilar",
  "Pilar",
  "Pinamar",
  "Piquete Cabado",
  "Platanos",
  "Plaza Huincul",
  "Plottier",
  "Pontevedra",
  "Portena",
  "Posadas",
  "Pozo del Molle",
  "Presidente Derqui",
  "Puan",
  "Pueblo San Jose",
  "Puerto Madryn",
  "Puerto Rico",
  "Pueyrredon",
  "Punta Alta",
  "Quilmes",
  "Rada Tilly",
  "Rafael Calzada",
  "Rafael Castillo",
  "Rafael Obligado",
  "Rafaela",
  "Ramallo",
  "Ramos Mejia",
  "Ranchos",
  "Rancul",
  "Ranelagh",
  "Rawson",
  "Rawson",
  "Realico",
  "Recoleta",
  "Reconquista",
  "Remedios de Escalada",
  "Resistencia",
  "Retiro",
  "Rio Ceballos",
  "Rio Colorado",
  "Rio Grande",
  "Rio Piedras",
  "Rio Segundo",
  "Rio Tercero",
  "Rivadavia",
  "Rivadavia",
  "Rivadavia",
  "Rocamora",
  "Rodriguez Pena",
  "Rojas",
  "Roldan",
  "Roque Perez",
  "Rosario",
  "Rosas",
  "Rufino",
  "Sacanta",
  "Saenz Pena",
  "Saladillo",
  "Saladillo",
  "Salguero",
  "Salsipuedes",
  "Salta",
  "Salto",
  "Salto Grande",
  "Sampacho",
  "San Andres",
  "San Andres de Giles",
  "San Antonio de Areco",
  "San Antonio de Arredondo",
  "San Antonio de Obligado",
  "San Antonio de Padua",
  "San Antonio Oeste",
  "San Benito",
  "San Bernardo",
  "San Carlos de Bolivar",
  "San Cayetano",
  "San Clemente",
  "San Cristobal",
  "San Fernando",
  "San Fernando del Valle de Catamarca",
  "San Francisco",
  "San Francisco de Santa Fe",
  "San Francisco Solano",
  "San Genaro",
  "San Gregorio",
  "San Guillermo",
  "San Isidro",
  "San Isidro",
  "San Isidro de Lules",
  "San Javier",
  "San Jeronimo Norte",
  "San Jorge",
  "San Jose",
  "San Jose de la Esquina",
  "San Juan",
  "San Justo",
  "San Lorenzo",
  "San Luis",
  "San Manuel",
  "San Martin",
  "San Martin de las Escobas",
  "San Miguel",
  "San Miguel",
  "San Miguel",
  "San Miguel del Monte",
  "San Nicolas",
  "San Pedro",
  "San Pedro",
  "San Rafael",
  "San Salvador",
  "San Salvador",
  "San Salvador de Jujuy",
  "San Telmo",
  "San Vicente",
  "Sanchez",
  "Santa Clara de Saguier",
  "Santa Elena",
  "Santa Fe",
  "Santa Lucia",
  "Santa Lucia",
  "Santa Rita",
  "Santa Rosa",
  "Santa Teresita",
  "Santiago del Estero",
  "Santo Tome",
  "Santos Lugares",
  "Sarandi",
  "Sarmiento",
  "Sarmiento",
  "Segui",
  "Sierra de la Ventana",
  "Sierra de los Padres",
  "Sinsacate",
  "Suipacha",
  "Sunchales",
  "Tablada",
  "Tacuari",
  "Tafi Viejo",
  "Tandil",
  "Tapalque",
  "Tapiales",
  "Temperley",
  "Teodelina",
  "Thames",
  "Tigre",
  "Tio Pujio",
  "Todd",
  "Tornquist",
  "Tortuguitas",
  "Tostado",
  "Totoras",
  "Trelew",
  "Trenque Lauquen",
  "Tres Arroyos",
  "Trevelin",
  "Tristan Suarez",
  "Tunuyan",
  "Tupungato",
  "Turdera",
  "Ucacha",
  "Uriburu",
  "Ushuaia",
  "Valle Hermoso",
  "Vedia",
  "Veinticinco de Mayo",
  "Veinticinco de Mayo",
  "Venado Tuerto",
  "Vera",
  "Veronica",
  "Viale",
  "Viamonte",
  "Vicente Lopez",
  "Victoria",
  "Victoria",
  "Vicuna Mackenna",
  "Viedma",
  "Villa Aberastain",
  "Villa Adelina",
  "Villa Allende",
  "Villa Alsina",
  "Villa Amelia",
  "Villa Angela",
  "Villa Ballester",
  "Villa Bosch",
  "Villa Canas",
  "Villa Carlos Paz",
  "Villa Constitucion",
  "Villa de Maria",
  "Villa de Mayo",
  "Villa del Parque",
  "Villa Dolores",
  "Villa Dominico",
  "Villa Elisa",
  "Villa General Belgrano",
  "Villa Gesell",
  "Villa Giardino",
  "Villa Huidobro",
  "Villa Insuperable",
  "Villa La Angostura",
  "Villa Las Rosas",
  "Villa Lugano",
  "Villa Luzuriaga",
  "Villa Madero",
  "Villa Maria Grande",
  "Villa Media Agua",
  "Villa Mercedes",
  "Villa Mercedes",
  "Villa Nueva",
  "Villa Nueva",
  "Villa Ocampo",
  "Villa Paranacito",
  "Villa Regina",
  "Villa Robles",
  "Villa Rosa",
  "Villa Trinidad",
  "Villa Urquiza",
  "Villaguay",
  "Vuelta de Obligado",
  "Warnes",
  "Wheelwright",
  "Wilde",
  "Winifreda",
  "Yerba Buena",
  "Zenon Pereyra",
  "Abovyan",
  "Agarak",
  "Apaga",
  "Aparan",
  "Arabkir",
  "Ashtarak",
  "Erebuni Fortress",
  "Hrazdan",
  "Ijevan",
  "Jermuk",
  "Kapan",
  "Tsaghkadzor",
  "Vanadzor",
  "Yerevan",
  "Noord",
  "Oranjestad",
  "Palm Beach",
  "Paradera",
  "Ponton",
  "Sabaneta",
  "San Barbola",
  "Santa Cruz",
  "Sero Blanco",
  "Sint Nicolaas",
  "Tanki Lender",
  "Abbotsford",
  "Abbotsford",
  "Abbotsham",
  "Aberdeen",
  "Aberfoyle",
  "Aberglasslyn",
  "Abermain",
  "Acacia Ridge",
  "Adamstown",
  "Adelaide",
  "Adelong",
  "Advancetown",
  "Agnes Banks",
  "Agnes Water",
  "Airlie Beach",
  "Aitkenvale",
  "Albany",
  "Albany Creek",
  "Albert Park",
  "Alberton",
  "Alberton",
  "Albion",
  "Albion Park",
  "Albury",
  "Aldgate",
  "Aldinga",
  "Aldinga Beach",
  "Alexandra",
  "Alexandra",
  "Alexandria",
  "Alfredton",
  "Alice Springs",
  "Allambee",
  "Allansford",
  "Allanson",
  "Allora",
  "Alma",
  "Alphington",
  "Alpine",
  "Alstonville",
  "Alton Downs",
  "Altona",
  "Amamoor",
  "Amaroo",
  "Angaston",
  "Anglesea",
  "Anna Bay",
  "Annandale",
  "Apollo Bay",
  "Applecross",
  "Applethorpe",
  "Ararat",
  "Arcadia",
  "Argents Hill",
  "Armadale",
  "Armadale",
  "Armidale",
  "Armstrong Creek",
  "Arno Bay",
  "Arrawarra",
  "Artarmon",
  "Ascot",
  "Ascot Vale",
  "Ashburton",
  "Ashfield",
  "Ashgrove",
  "Ashton",
  "Aspendale",
  "Aspley",
  "Asquith",
  "Atherton",
  "Attadale",
  "Auburn",
  "Augusta",
  "Austinmer",
  "Austins Ferry",
  "Australind",
  "Avalon",
  "Avenue",
  "Avoca Beach",
  "Avondale",
  "Axedale",
  "Aylmerton",
  "Ayr",
  "Babinda",
  "Bacchus Marsh",
  "Bagdad",
  "Bahrs Scrub",
  "Bairnsdale",
  "Baker",
  "Balaclava",
  "Balaklava",
  "Bald Hills",
  "Balgowlah",
  "Balgownie",
  "Balhannah",
  "Ballan",
  "Ballarat",
  "Ballina",
  "Balmain",
  "Balmoral",
  "Balnarring",
  "Balwyn",
  "Balwyn North",
  "Bangalow",
  "Bangor",
  "Banksmeadow",
  "Bankstown",
  "Bannockburn",
  "Barcoo",
  "Barellan",
  "Bargara",
  "Bargo",
  "Baringhup",
  "Barkstead",
  "Barnsley",
  "Barry",
  "Barwon Downs",
  "Barwon Heads",
  "Barwon Heads",
  "Basin View",
  "Bass Hill",
  "Bassendean",
  "Batchelor",
  "Bateau Bay",
  "Batesford",
  "Bathurst",
  "Batlow",
  "Baulkham Hills",
  "Baxter",
  "Bayles",
  "Baynton",
  "Bayswater",
  "Beachmere",
  "Beacon",
  "Beaconsfield",
  "Beaconsfield Upper",
  "Beaudesert",
  "Beaumaris",
  "Beaumont",
  "Beaumont",
  "Beauty Point",
  "Bedford Park",
  "Bedfordale",
  "Beeac",
  "Beechwood",
  "Beechworth",
  "Beenak",
  "Beenleigh",
  "Beerwah",
  "Bega",
  "Belair",
  "Belconnen",
  "Belgian Gardens",
  "Belgrave",
  "Belgrave Heights",
  "Bell",
  "Bellambi",
  "Bellara",
  "Bellbird",
  "Bellbrae",
  "Bellerive",
  "Bellevue Hill",
  "Belmont",
  "Belmont",
  "Belmont",
  "Belrose",
  "Benalla",
  "Benambra",
  "Bendigo",
  "Benowa",
  "Bensville",
  "Bentleigh",
  "Bentleigh East",
  "Bentley",
  "Bentley",
  "Beresfield",
  "Berkeley",
  "Berkeley Vale",
  "Berowra",
  "Berridale",
  "Berrima",
  "Berry",
  "Berwick",
  "Bethania Junction",
  "Beveridge",
  "Beverley",
  "Beverley",
  "Bexley",
  "Bicheno",
  "Bicton",
  "Big Pats Creek",
  "Bilinga",
  "Biloela",
  "Bilpin",
  "Binda",
  "Binnaway",
  "Birdwood",
  "Birkdale",
  "Birkenhead",
  "Black Hill",
  "Black Rock",
  "Blackburn",
  "Blackbutt",
  "Blackheath",
  "Blackmans Bay",
  "Blacktown",
  "Blackwall",
  "Blackwarry",
  "Blackwater",
  "Blackwood",
  "Blackwood",
  "Blair Athol",
  "Blair Athol",
  "Blakehurst",
  "Blaxland",
  "Blayney",
  "Bli Bli",
  "Boambee",
  "Boat Harbour",
  "Bobin",
  "Boddington",
  "Bogangar",
  "Bohle Plains",
  "Bolton",
  "Bolwarra",
  "Bomaderry",
  "Bombala",
  "Bonbeach",
  "Bondi",
  "Boneo",
  "Bongaree",
  "Bonnells Bay",
  "Bonnet Bay",
  "Bonython",
  "Booker Bay",
  "Bool Lagoon",
  "Boolarra",
  "Boonah",
  "Boondall",
  "Booral",
  "Bordertown",
  "Boronia",
  "Botany",
  "Boulder",
  "Bourke",
  "Bowen",
  "Bowenfels",
  "Bowral",
  "Bowraville",
  "Box Hill",
  "Box Hill South",
  "Boyup Brook",
  "Bradbury",
  "Braddon",
  "Braeside",
  "Braidwood",
  "Brandon",
  "Brandy Hill",
  "Branxton",
  "Brewarrina",
  "Briar Hill",
  "Bridgetown",
  "Bridgewater",
  "Bridgewater",
  "Brighton",
  "Brighton",
  "Brighton",
  "Brighton East",
  "Brighton-Le-Sands",
  "Bringelly",
  "Brisbane",
  "Broadbeach",
  "Broadford",
  "Broadmeadows",
  "Broadwater",
  "Broadwater",
  "Broke",
  "Broken Hill",
  "Bronte",
  "Brookdale",
  "Brookfield",
  "Brookfield",
  "Brooklyn",
  "Brookvale",
  "Broome",
  "Brown Hill",
  "Browns Plains",
  "Bruce",
  "Brunswick",
  "Buchan",
  "Buckland",
  "Buderim",
  "Budgewoi",
  "Bulahdelah",
  "Bulga",
  "Bulimba",
  "Bulla",
  "Bulleen",
  "Bulli",
  "Bullsbrook",
  "Bullyard",
  "Buln Buln",
  "Bunbury",
  "Bundaberg",
  "Bundalong",
  "Bundamba",
  "Bundanoon",
  "Bundeena",
  "Bundook",
  "Bundoora",
  "Bungendore",
  "Bungonia",
  "Buninyong",
  "Burekup",
  "Burleigh Heads",
  "Burnett Heads",
  "Burnie",
  "Burnley",
  "Burnside",
  "Burpengary",
  "Burradoo",
  "Burraneer",
  "Burrum",
  "Burrum Heads",
  "Burwood",
  "Burwood",
  "Bushland Beach",
  "Busselton",
  "Butchers Ridge",
  "Buxton",
  "Byford",
  "Byron Bay",
  "Caboolture",
  "Cairns",
  "Calen",
  "Calingiri",
  "Callala Bay",
  "Callington",
  "Caloundra",
  "Caltowie",
  "Camberwell",
  "Cambewarra",
  "Cambridge",
  "Camden",
  "Camden Haven",
  "Cammeray",
  "Campbell",
  "Campbellfield",
  "Campbelltown",
  "Campbelltown",
  "Campbelltown",
  "Camperdown",
  "Camperdown",
  "Canadian",
  "Canberra",
  "Cannington",
  "Cannonvale",
  "Canterbury",
  "Canterbury",
  "Canungra",
  "Capalaba",
  "Caragabal",
  "Caravonica",
  "Carbrook",
  "Cardiff",
  "Cardigan",
  "Cardinia",
  "Cardup",
  "Caringbah",
  "Carlingford",
  "Carlsruhe",
  "Carlton",
  "Carlton North",
  "Carlton South",
  "Carnarvon",
  "Carnegie",
  "Caroline Springs",
  "Carrick",
  "Carrington",
  "Carrum",
  "Carrum Downs",
  "Casino",
  "Casterton",
  "Castle Hill",
  "Castlecrag",
  "Castlemaine",
  "Caulfield",
  "Caulfield North",
  "Caulfield South",
  "Caversham",
  "Cawarral",
  "Cawongla",
  "Cedar Grove",
  "Ceduna",
  "Central Coast",
  "Cessnock",
  "Charlestown",
  "Chatswood",
  "Chatsworth Island",
  "Chelsea",
  "Cheltenham",
  "Chinchilla",
  "Chippendale",
  "Chipping Norton",
  "Christies",
  "Chullora",
  "Churchill",
  "City of Parramatta",
  "City of West Torrens",
  "Clare",
  "Clare",
  "Claremont",
  "Claremont",
  "Clarence Town",
  "Clareville",
  "Clarinda",
  "Clarkefield",
  "Clayton North",
  "Cleveland",
  "Clifton",
  "Clifton Hill",
  "Clifton Springs",
  "Clontarf",
  "Clontarf",
  "Closeburn",
  "Clovelly",
  "Clunes",
  "Clyde",
  "Clyde",
  "Clyde North",
  "Cobbitty",
  "Coburg",
  "Cockatoo",
  "Cockburn",
  "Coffs Harbour",
  "Colac",
  "Coleambally",
  "Coledale",
  "Coleraine",
  "Collaroy",
  "Collie",
  "Collingwood",
  "Collinsvale",
  "Colo",
  "Colo Vale",
  "Como",
  "Concord",
  "Condamine",
  "Condobolin",
  "Coniston",
  "Connells Point",
  "Coober Pedy",
  "Cooee",
  "Coogee",
  "Coogee",
  "Cook",
  "Cooktown",
  "Coolah",
  "Coolamon",
  "Coolangatta",
  "Cooloolabin",
  "Coolum",
  "Coolum Beach",
  "Coolup",
  "Cooma",
  "Coomera",
  "Coonawarra",
  "Coondoo",
  "Cooranbong",
  "Cooroy",
  "Coorparoo",
  "Cootamundra",
  "Copacabana",
  "Copmanhurst",
  "Corinda",
  "Corinthia",
  "Corio",
  "Corlette",
  "Coromandel Valley",
  "Corrimal",
  "Cotham",
  "Cottesloe",
  "Coutts Crossing",
  "Cowan",
  "Cowes",
  "Cowra",
  "Crafers",
  "Craigieburn",
  "Cranbourne",
  "Crawford",
  "Cremorne",
  "Cremorne",
  "Crescent Head",
  "Creswick",
  "Crib Point",
  "Cringila",
  "Cronulla",
  "Crookwell",
  "Crossley",
  "Crows Nest",
  "Crows Nest",
  "Croydon",
  "Croydon",
  "Croydon North",
  "Crystal Creek",
  "Cudlee Creek",
  "Cummins",
  "Cundletown",
  "Curl Curl",
  "Currumbin",
  "Cygnet",
  "Daceyville",
  "Daisy Hill",
  "Dakabin",
  "Dalby",
  "Dalkeith",
  "Dandenong",
  "Dapto",
  "Dardanup",
  "Darkan",
  "Darley",
  "Darling",
  "Darling Point",
  "Darlinghurst",
  "Darlington",
  "Darlington",
  "Darra",
  "Darwin",
  "Davidson",
  "Davistown",
  "Dawson",
  "Dayboro",
  "Daylesford",
  "Deagon",
  "Deakin",
  "Deception Bay",
  "Deepdene",
  "Deer Park",
  "Deloraine",
  "Denham",
  "Denman",
  "Dereel",
  "Derrimut",
  "Derwent",
  "Devonport",
  "Diamond Creek",
  "Diggers Rest",
  "Dilston",
  "Dimboola",
  "Dimbulah",
  "Dingley",
  "Dirranbandi",
  "Dodges Ferry",
  "Dolans Bay",
  "Don",
  "Doncaster",
  "Doncaster East",
  "Donnybrook",
  "Donvale",
  "Doonside",
  "Doreen",
  "Dorrigo",
  "Doubtful Creek",
  "Douglas",
  "Douglas Park",
  "Dover Heights",
  "Drayton",
  "Dromana",
  "Drouin",
  "Drouin South",
  "Drouin West",
  "Drummond Cove",
  "Drummoyne",
  "Drysdale",
  "Dubbo",
  "Dumbalk",
  "Dumbleyung",
  "Dundas",
  "Dundowran",
  "Dungog",
  "Dunkeld",
  "Dunmore",
  "Dunolly",
  "Dunsborough",
  "Dural",
  "Eagle Farm",
  "Eagle Heights",
  "Eagleby",
  "Eaglehawk",
  "Eaglemont",
  "Earlwood",
  "East Fremantle",
  "East Gosford",
  "East Maitland",
  "East Malvern",
  "Eastwood",
  "Eaton",
  "Ebbw Vale",
  "Ebenezer",
  "Echuca",
  "Echunga",
  "Eden",
  "Eden Park",
  "Edge Hill",
  "Edgecliff",
  "Edith",
  "Edithvale",
  "Edmonton",
  "Edwardstown",
  "Eight Mile Plains",
  "Elderslie",
  "Elizabeth",
  "Ellalong",
  "Ellangowan",
  "Ellendale",
  "Ellerslie",
  "Elsternwick",
  "Elsternwick",
  "Eltham",
  "Eltham North",
  "Elwood",
  "Emerald",
  "Emerald",
  "Empire Bay",
  "Emu Park",
  "Emu Plains",
  "Emu Vale",
  "Encounter Bay",
  "Endeavour",
  "Endeavour Hills",
  "Enfield",
  "Engadine",
  "Enmore",
  "Enoggera",
  "Epping",
  "Epping",
  "Erina",
  "Erskine",
  "Eschol",
  "Esk",
  "Esperance",
  "Essendon",
  "Ettalong Beach",
  "Eudlo",
  "Eudunda",
  "Eumundi",
  "Euroa",
  "Evandale",
  "Everton",
  "Exeter",
  "Exmouth",
  "Failford",
  "Fairfield",
  "Fairfield",
  "Fairview",
  "Fairy Meadow",
  "Fassifern",
  "Faulconbridge",
  "Fawkner",
  "Fern Tree",
  "Fern Tree Gully",
  "Ferndale",
  "Ferntree Gully",
  "Fernvale",
  "Ferny Creek",
  "Figtree",
  "Findon",
  "Fingal",
  "Fingal Bay",
  "Fitzroy",
  "Flemington",
  "Flinders",
  "Flinders",
  "Flynn",
  "Footscray",
  "Forbes",
  "Forest",
  "Forest Hill",
  "Forestville",
  "Forrest",
  "Forrest",
  "Forsayth",
  "Forster",
  "Foster",
  "Franklin",
  "Frankston",
  "Freeling",
  "Freemans Reach",
  "Fremantle",
  "Freshwater",
  "Fulham",
  "Fullerton",
  "Fyshwick",
  "Galston",
  "Garfield",
  "Gatton",
  "Gawler",
  "Gayndah",
  "Gaythorne",
  "Geelong",
  "Geelong West",
  "Gellibrand",
  "George Town",
  "Gepps Cross",
  "Geraldton",
  "Gerringong",
  "Gheerulla",
  "Gilberton",
  "Gilmore",
  "Gilston",
  "Gin Gin",
  "Girraween",
  "Gisborne",
  "Gladesville",
  "Gladstone",
  "Glass House Mountains",
  "Glebe",
  "Glen Huntly",
  "Glen Huon",
  "Glen Innes",
  "Glen Iris",
  "Glen Osmond",
  "Glen Waverley",
  "Glenbrook",
  "Glenburn",
  "Glenelg",
  "Glenfield",
  "Glengarry",
  "Glenhaven",
  "Glenorchy",
  "Glenorchy",
  "Glenore Grove",
  "Glenorie",
  "Glenreagh",
  "Glenroy",
  "Glenvale",
  "Glossodia",
  "Gloucester",
  "Golconda",
  "Gold Coast",
  "Golden Grove",
  "Goodna",
  "Goodwood",
  "Goolwa",
  "Goomeri",
  "Goonellabah",
  "Goornong",
  "Gooseberry Hill",
  "Gordon",
  "Gordon",
  "Gordonvale",
  "Gore Hill",
  "Gorokan",
  "Gosford",
  "Gosforth",
  "Gosnells",
  "Goulburn",
  "Gould",
  "Gowrie",
  "Gracemere",
  "Grafton",
  "Grandchester",
  "Grange",
  "Grant",
  "Grantham",
  "Granville",
  "Grassmere",
  "Gravesend",
  "Green Hill",
  "Green Point",
  "Greenbank",
  "Greendale",
  "Greensborough",
  "Greenvale",
  "Greenwich",
  "Gregadoo",
  "Grenfell",
  "Greta",
  "Griffith",
  "Grove",
  "Grovedale",
  "Guildford",
  "Guildford",
  "Gundaroo",
  "Gunnedah",
  "Gymea",
  "Gymea Bay",
  "Gympie",
  "Haberfield",
  "Hackham",
  "Haddon",
  "Hadspen",
  "Hagley",
  "Hahndorf",
  "Hall",
  "Hallam",
  "Hallett",
  "Halls Gap",
  "Hamilton",
  "Hamilton",
  "Hamilton",
  "Hamilton",
  "Hammond",
  "Hampton",
  "Hampton Park",
  "Happy Valley",
  "Harrington",
  "Harristown",
  "Harvey",
  "Hastings",
  "Hastings Point",
  "Hat Head",
  "Hawker",
  "Hawkesbury Heights",
  "Hawksburn",
  "Hawthorn",
  "Hawthorne",
  "Haymarket",
  "Hazelbrook",
  "Hazelwood",
  "Healesville",
  "Heathcote",
  "Heathcote",
  "Heathcote Junction",
  "Heatherton",
  "Heathmont",
  "Heddon Greta",
  "Heidelberg",
  "Helensburgh",
  "Helensvale",
  "Hendon",
  "Hepburn Springs",
  "Hervey Bay",
  "Hexham",
  "Highbury",
  "Highett",
  "Highfields",
  "Hill Top",
  "Hillcrest",
  "Hindmarsh",
  "Hobart",
  "Hoddles Creek",
  "Hollow Tree",
  "Holroyd",
  "Holsworthy",
  "Homebush",
  "Homebush",
  "Hope Island",
  "Hope Valley",
  "Hopetoun",
  "Hoppers Crossing",
  "Hornsby",
  "Horsham",
  "Hove",
  "Howard",
  "Howard Springs",
  "Howden",
  "Howe",
  "Howlong",
  "Hughesdale",
  "Hunter",
  "Hunters Hill",
  "Huntly",
  "Huonville",
  "Hurstbridge",
  "Hurstville",
  "Hurstville Grove",
  "Hyland Park",
  "Illawarra",
  "Illawong",
  "Iluka",
  "Indented Head",
  "Ingham",
  "Ingle Farm",
  "Ingleburn",
  "Inglewood",
  "Innisfail",
  "Inverell",
  "Inverloch",
  "Invermay",
  "Ipswich",
  "Isabella",
  "Ivanhoe",
  "Ivanhoe East",
  "Ives",
  "Jacobs Well",
  "Jannali",
  "Jarrahdale",
  "Jensen",
  "Jilliby",
  "Jimboomba",
  "Jindabyne",
  "Jindivick",
  "Judbury",
  "Junee",
  "Kadina",
  "Kalgoorlie",
  "Kallista",
  "Kalorama",
  "Kambalda",
  "Kangaroo Flat",
  "Kangaroo Point",
  "Kanwal",
  "Kapunda",
  "Karalee",
  "Karana Downs",
  "Kardella",
  "Kardella South",
  "Kareela",
  "Karnup",
  "Karoonda",
  "Karratha",
  "Katherine",
  "Katoomba",
  "Kawungan",
  "Keilor",
  "Keiraville",
  "Keith",
  "Kellyville",
  "Kelmscott",
  "Kelso",
  "Kelvin Grove",
  "Kempsey",
  "Kempton",
  "Kendall",
  "Kenilworth",
  "Kenmore",
  "Kennington",
  "Kensington",
  "Kensington",
  "Kensington and Norwood",
  "Kenthurst",
  "Kenwick",
  "Kerang",
  "Kerry",
  "Keswick",
  "Kettering",
  "Kew",
  "Kew",
  "Kew East",
  "Keysborough",
  "Keysbrook",
  "Kiama",
  "Kilcoy",
  "Kilcunda",
  "Killara",
  "Killarney",
  "Killarney",
  "Killcare",
  "Killingworth",
  "Kilmore",
  "Kilsyth",
  "Kincumber",
  "Kindred",
  "Kingaroy",
  "Kinglake",
  "Kings Cross",
  "Kings Park",
  "Kingscliff",
  "Kingsthorpe",
  "Kingston",
  "Kingston",
  "Kingston",
  "Kingston",
  "Kingswood",
  "Kinross",
  "Kirrawee",
  "Kirribilli",
  "Kirwan",
  "Koah",
  "Kobble",
  "Koetong",
  "Kogarah",
  "Kojonup",
  "Koo-Wee-Rup",
  "Koolewong",
  "Koorawatha",
  "Koornalla",
  "Kootingal",
  "Kooyong",
  "Koroit",
  "Korumburra",
  "Kotara",
  "Kununurra",
  "Kuranda",
  "Kurnell",
  "Kurrajong Heights",
  "Kurri Kurri",
  "Kyabram",
  "Kyneton",
  "Kyogle",
  "Laang",
  "Laguna",
  "Laidley",
  "Lake Cathie",
  "Lake Heights",
  "Lake Illawarra",
  "Lake Munmorah",
  "Lakemba",
  "Lakes Entrance",
  "Lalor",
  "Lambton",
  "Lamington",
  "Lancefield",
  "Lancelin",
  "Landsborough",
  "Lane Cove",
  "Lang Lang",
  "Langhorne Creek",
  "Langley",
  "Langwarrin",
  "Lara",
  "Largs North",
  "Latrobe",
  "Lauderdale",
  "Launceston",
  "Laverton",
  "Laverton",
  "Lavington",
  "Lawgi",
  "Lawnton",
  "Lawson",
  "Lebrina",
  "Leeton",
  "Legana",
  "Leichhardt",
  "Lemon Tree Passage",
  "Lennox Head",
  "Leongatha",
  "Leopold",
  "Lethbridge",
  "Leumeah",
  "Leura",
  "Lewiston",
  "Lidcombe",
  "Lilli Pilli",
  "Lilydale",
  "Limestone",
  "Linden",
  "Lindenow",
  "Lindfield",
  "Lindisfarne",
  "Lisarow",
  "Lismore",
  "Lithgow",
  "Little Bay",
  "Little Hampton",
  "Little River",
  "Liverpool",
  "Loch",
  "Lockhart",
  "Lockridge",
  "Loftus",
  "Logan",
  "Logan City",
  "Logan Village",
  "Loganholme",
  "Loganlea",
  "Long Jetty",
  "Long Plains",
  "Long Point",
  "Longford",
  "Longreach",
  "Longueville",
  "Longwarry",
  "Lovely Banks",
  "Lowanna",
  "Lower Chittering",
  "Lower Plenty",
  "Lowood",
  "Loxton",
  "Luddenham",
  "Ludlow",
  "Lugarno",
  "Lulworth",
  "Lutana",
  "Lyndhurst",
  "Lyndoch",
  "Lyneham",
  "Lyons",
  "Lysterfield",
  "Macarthur",
  "Macedon",
  "Mackay",
  "Macksville",
  "Maclean",
  "Macleod",
  "Macquarie Park",
  "Maddington",
  "Maffra",
  "Magill",
  "Maidenwell",
  "Maitland",
  "Malabar",
  "Maleny",
  "Mallala",
  "Mallanganee",
  "Malmsbury",
  "Malvern",
  "Mandalong",
  "Mandurah",
  "Mangalore",
  "Mangerton",
  "Manildra",
  "Manjimup",
  "Manly",
  "Manly",
  "Mannering Park",
  "Manning",
  "Manning Point",
  "Mannum",
  "Mansfield",
  "Mapleton",
  "Mareeba",
  "Margaret River",
  "Margate",
  "Margate",
  "Marian",
  "Maribyrnong",
  "Marino",
  "Marion",
  "Marlee",
  "Marmor",
  "Marong",
  "Maroochydore",
  "Maroota",
  "Maroubra",
  "Marrickville",
  "Marsden",
  "Marsden Park",
  "Marshalltown",
  "Martins Creek",
  "Marulan",
  "Maryborough",
  "Maryborough",
  "Maryland",
  "Marysville",
  "Mascot",
  "Maslin Beach",
  "Matcham",
  "Matraville",
  "Maudsland",
  "Maybole",
  "Mayfield",
  "Maylands",
  "McCrae",
  "McGraths Hill",
  "McKinnon",
  "McLachlan",
  "McLaren Flat",
  "McLaren Vale",
  "Meadows",
  "Medlow Bath",
  "Medowie",
  "Melbourne",
  "Melrose",
  "Melton",
  "Melton South",
  "Melville",
  "Menai",
  "Menangle",
  "Mentone",
  "Meredith",
  "Merewether",
  "Meringandan",
  "Merlynston",
  "Mernda",
  "Merredin",
  "Merriwa",
  "Merrylands",
  "Middlemount",
  "Middleton",
  "Middleton",
  "Midway Point",
  "Mildura",
  "Mile End",
  "Miles",
  "Milton",
  "Miners Rest",
  "Minlaton",
  "Minmi",
  "Minto",
  "Miranda",
  "Mirani",
  "Mirboo",
  "Mirboo North",
  "Mirrabooka",
  "Mission Beach",
  "Mitcham",
  "Mitcham",
  "Mitchell",
  "Mitchelton",
  "Mitiamo",
  "Mittagong",
  "Moama",
  "Moana",
  "Modbury",
  "Moggill",
  "Mona Vale",
  "Monash",
  "Monbulk",
  "Mont Albert North",
  "Monteagle",
  "Monterey",
  "Montmorency",
  "Montrose",
  "Montville",
  "Mooloolaba",
  "Mooloolah Valley",
  "Moonah",
  "Moonee Ponds",
  "Mooney Mooney",
  "Moorabbin",
  "Mooralla",
  "Moore",
  "Moore Park",
  "Moorooduc",
  "Mooroolbark",
  "Mooroopna",
  "Mooroopna",
  "Moranbah",
  "Morang",
  "Morayfield",
  "Mordialloc",
  "Moree",
  "Moriac",
  "Morisset",
  "Mornington",
  "Morphett Vale",
  "Mortdale",
  "Mortlake",
  "Moruya",
  "Morwell",
  "Mosman",
  "Mosman Park",
  "Moss Vale",
  "Mossman",
  "Mount Barker",
  "Mount Colah",
  "Mount Cotton",
  "Mount Dandenong",
  "Mount Direction",
  "Mount Druitt",
  "Mount Egerton",
  "Mount Eliza",
  "Mount Evelyn",
  "Mount Gambier",
  "Mount Gravatt",
  "Mount Helen",
  "Mount Helena",
  "Mount Isa",
  "Mount Julian",
  "Mount Keira",
  "Mount Larcom",
  "Mount Lofty",
  "Mount Macedon",
  "Mount Martha",
  "Mount Molloy",
  "Mount Morgan",
  "Mount Ousley",
  "Mount Perry",
  "Mount Pleasant",
  "Mount Saint Thomas",
  "Mount Waverley",
  "Mount White",
  "Mourilyan",
  "Muchea",
  "Mudgee",
  "Mudgeeraba",
  "Mudjimba",
  "Mulgoa",
  "Mulgrave",
  "Mullewa",
  "Mullumbimby",
  "Mundaring",
  "Mundijong",
  "Murray Bridge",
  "Murrumba",
  "Murrumbateman",
  "Murrumbeena",
  "Murrurundi",
  "Murtoa",
  "Murwillumbah",
  "Muswellbrook",
  "Mylor",
  "Myrrhee",
  "Myrtleford",
  "Nagambie",
  "Nairne",
  "Nambour",
  "Nambucca Heads",
  "Nana Glen",
  "Nanango",
  "Nannup",
  "Napoleons",
  "Nar Nar Goon",
  "Narangba",
  "Narara",
  "Narellan",
  "Narooma",
  "Narrabeen",
  "Narrabri",
  "Narrandera",
  "Narrawong",
  "Narre Warren",
  "Narre Warren North",
  "Narrogin",
  "Narromine",
  "Neath",
  "Nebo",
  "Nedlands",
  "Neerim South",
  "Nelson Bay",
  "Nerang",
  "Nerrigundah",
  "Nerrina",
  "Neutral Bay",
  "New Farm",
  "New Lambton",
  "New Town",
  "Newcastle",
  "Newmarket",
  "Newnham",
  "Newport",
  "Newport",
  "Newry",
  "Newstead",
  "Newstead",
  "Newstead",
  "Newtown",
  "Newtown",
  "Nhill",
  "Nindaroo",
  "Ningi",
  "Nirranda",
  "Noarlunga",
  "Noble Park",
  "Noosa",
  "Noosaville",
  "Norah",
  "Nords Wharf",
  "Norlane",
  "Norman Park",
  "Normanhurst",
  "Normanton",
  "Normanville",
  "North Beach",
  "North Fitzroy",
  "North Mackay",
  "North Melbourne",
  "North Tamborine",
  "North Turramurra",
  "Northam",
  "Northcote",
  "Northgate",
  "Northmead",
  "Norton Summit",
  "Norwood",
  "Notting Hill",
  "Nowra",
  "Nullawarre",
  "Nunawading",
  "Nuriootpa",
  "Nyora",
  "Oak Park",
  "Oakdale",
  "Oakey",
  "Oakhurst",
  "Oaklands",
  "Oakleigh",
  "Oakleigh South",
  "Oatlands",
  "Oatley",
  "Oberon",
  "Obi Obi",
  "Ocean Shores",
  "Officer",
  "Old Bar",
  "Old Beach",
  "Olinda",
  "Oman-Ama",
  "One Tree Hill",
  "Orange",
  "Orchard Hills",
  "Orford",
  "Orient Point",
  "Ormeau",
  "Ormiston",
  "Ormond",
  "Orroroo",
  "Osborne",
  "Ourimbah",
  "Oxenford",
  "Oxley",
  "Oxley",
  "Oyster Bay",
  "Paddington",
  "Padstow",
  "Pakenham",
  "Pallarenda",
  "Palm Beach",
  "Palm Cove",
  "Palm Island",
  "Palmer",
  "Palmwoods",
  "Pambula",
  "Paradise",
  "Paramatta",
  "Parap",
  "Park Ridge",
  "Parkdale",
  "Parkerville",
  "Parkes",
  "Parkhurst",
  "Parkville",
  "Parkwood",
  "Pearce",
  "Pearcedale",
  "Pechey",
  "Pelican",
  "Pendle Hills",
  "Penfield",
  "Penguin",
  "Pennant Hills",
  "Penrith",
  "Penshurst",
  "Perenjori",
  "Perth",
  "Perth",
  "Peterborough",
  "Petrie",
  "Phillip",
  "Pialba",
  "Piawaning",
  "Picnic Bay",
  "Picton",
  "Piggabeen",
  "Pimpama",
  "Pine Mountain",
  "Pinery",
  "Pinjarra",
  "Pinkenba",
  "Pioneer",
  "Pipers Brook",
  "Pitt Town",
  "Pittsworth",
  "Plympton",
  "Point Clare",
  "Point Cook",
  "Point Lonsdale",
  "Point Lookout",
  "Point Pass",
  "Point Vernon",
  "Pokolbin",
  "Pomona",
  "Pontville",
  "Poowong",
  "Port Adelaide",
  "Port Augusta",
  "Port Douglas",
  "Port Fairy",
  "Port Hacking",
  "Port Hedland",
  "Port Kembla",
  "Port Lincoln",
  "Port MacDonnell",
  "Port Macquarie",
  "Port Melbourne",
  "Port Noarlunga",
  "Port Pirie",
  "Port Sorell",
  "Portarlington",
  "Portland",
  "Portsea",
  "Potts Point",
  "Prahran",
  "Preston",
  "Proserpine",
  "Prospect",
  "Purnim",
  "Pymble",
  "Pyrmont",
  "Quakers Hill",
  "Queanbeyan",
  "Queenscliff",
  "Queensferry",
  "Queenstown",
  "Railton",
  "Ramsgate",
  "Randwick",
  "Rathmines",
  "Ravenswood",
  "Raworth",
  "Raymond Terrace",
  "Red Hill",
  "Redan",
  "Redbank",
  "Redcliffe",
  "Redfern",
  "Redhead",
  "Redland Bay",
  "Redlynch",
  "Reedy Creek",
  "Regents Park",
  "Research",
  "Reservoir",
  "Retreat",
  "Revesby",
  "Reynella",
  "Rhodes",
  "Riana",
  "Richmond",
  "Richmond",
  "Riddell",
  "Ridgley",
  "Ringwood",
  "Ringwood East",
  "Ringwood North",
  "Ripley",
  "Risdon",
  "River Heads",
  "Riverside",
  "Riverstone",
  "Riverton",
  "Riverview",
  "Riverwood",
  "Robertson",
  "Robertstown",
  "Robinvale",
  "Rochedale",
  "Rochester",
  "Rockbank",
  "Rockdale",
  "Rockhampton",
  "Rockingham",
  "Rocklea",
  "Rodborough",
  "Rokeby",
  "Roleystone",
  "Roma",
  "Romsey",
  "Rooty Hill",
  "Rosanna",
  "Rose Bay",
  "Rosebery",
  "Rosebery",
  "Rosebud",
  "Rosehill",
  "Roseville",
  "Rosewood",
  "Roseworthy",
  "Ross",
  "Ross Creek",
  "Ross River",
  "Rowville",
  "Royal Park",
  "Rozelle",
  "Rudall",
  "Rushworth",
  "Rutherford",
  "Rydalmere",
  "Ryde",
  "Rye",
  "Rylstone",
  "Safety Bay",
  "Saint Albans",
  "Saint Andrews",
  "Saint George",
  "Saint Georges Basin",
  "Saint Helena",
  "Saint Ives",
  "Saint James",
  "Saint Leonards",
  "Saint Lucia",
  "Saint Marys",
  "Saint Peters",
  "Saints",
  "Salamander Bay",
  "Sale",
  "Salisbury",
  "Salt Ash",
  "Samford",
  "San Remo",
  "Sanctuary Point",
  "Sandford",
  "Sandgate",
  "Sandgate",
  "Sandringham",
  "Sandstone Point",
  "Sandy Bay",
  "Sandy Hollow",
  "Sans Souci",
  "Sapphire",
  "Sarina",
  "Sarina Beach",
  "Sassafras",
  "Scarborough",
  "Scarborough",
  "Scarness",
  "Scarsdale",
  "Schofields",
  "Scone",
  "Scoresby",
  "Scottsdale",
  "Seacliff",
  "Seacombe",
  "Seaford",
  "Seaford",
  "Seaforth",
  "Seaton",
  "Seaview",
  "Sebastopol",
  "Selbourne",
  "Selby",
  "Sellicks Beach",
  "Sellicks Hill",
  "Semaphore",
  "Serpentine",
  "Seven Hills",
  "Seven Mile Beach",
  "Seville",
  "Seville East",
  "Seymour",
  "Sheffield",
  "Shellharbour",
  "Shenton Park",
  "Sherbrook",
  "Shoal Point",
  "Shorncliffe",
  "Silvan",
  "Silverdale",
  "Silverwater",
  "Singleton",
  "Sippy Downs",
  "Slacks Creek",
  "Smithfield",
  "Smithfield",
  "Smithton",
  "Smythes Creek",
  "Smythesdale",
  "Snowtown",
  "Somersby",
  "Somerset",
  "Somerset",
  "Somerton",
  "Somerville",
  "Sorrento",
  "South Melbourne",
  "South Perth",
  "South West Rocks",
  "South Yarra",
  "Southbank",
  "Southern Brook",
  "Southport",
  "Spearwood",
  "Spencer",
  "Spotswood",
  "Spreyton",
  "Spring Field",
  "Spring Hill",
  "Spring Hill",
  "Springfield",
  "Springvale",
  "Springvale South",
  "Springwood",
  "St Helens",
  "St Kilda",
  "Stanhope",
  "Stanley",
  "Stanmore",
  "Stannum",
  "Stanthorpe",
  "Stapylton",
  "Stawell",
  "Stieglitz",
  "Stirling",
  "Stirling",
  "Stockton",
  "Stockyard Creek",
  "Stoneville",
  "Stradbroke",
  "Stratford",
  "Stratford",
  "Strathalbyn",
  "Strathfield",
  "Strathfieldsaye",
  "Strathmore",
  "Strathpine",
  "Streaky Bay",
  "Stroud",
  "Stuart Park",
  "Sturt",
  "Subiaco",
  "Success",
  "Suffolk Park",
  "Sulphur Creek",
  "Summerholm",
  "Summertown",
  "Sunbury",
  "Sunnybank",
  "Sunnyside",
  "Sunshine",
  "Surfers Paradise",
  "Surrey Hills",
  "Sutherland",
  "Swan Hill",
  "Swan View",
  "Swansea",
  "Swansea",
  "Sydenham",
  "Sydney",
  "Sylvania",
  "Sylvania Waters",
  "Tahmoor",
  "Tallangatta",
  "Tallarook",
  "Tallebudgera",
  "Talmalmo",
  "Tambo Upper",
  "Tamborine",
  "Tammin",
  "Tamworth",
  "Tannum Sands",
  "Tanunda",
  "Taree",
  "Taren Point",
  "Tarlee",
  "Tarneit",
  "Taroona",
  "Tarragindi",
  "Tarrawanna",
  "Tarro",
  "Tarzali",
  "Tatura",
  "Tawonga",
  "Teesdale",
  "Telegraph Point",
  "Temora",
  "Tempe",
  "Templestowe",
  "Templestowe Lower",
  "Tenambit",
  "Tennyson",
  "Tenterfield",
  "Teralba",
  "Terrigal",
  "Terry Hills",
  "Tewantin",
  "Thagoona",
  "Thargomindah",
  "The Basin",
  "The Entrance",
  "The Oaks",
  "The Patch",
  "The Rocks",
  "Thebarton",
  "Thirlmere",
  "Thirroul",
  "Thomastown",
  "Thompson",
  "Thornbury",
  "Thornlands",
  "Thornleigh",
  "Thornton",
  "Thuringowa",
  "Thursday Island",
  "Tiaro",
  "Tieri",
  "Tinamba",
  "Tincurrin",
  "Tingoora",
  "Tolga",
  "Tom Price",
  "Tomago",
  "Tongala",
  "Toogoolawah",
  "Toogoom",
  "Toolangi",
  "Toolern Vale",
  "Toongabbie",
  "Toora",
  "Tooradin",
  "Toorak",
  "Toorbul",
  "Tooronga",
  "Toowong",
  "Toowoomba",
  "Torbanlea",
  "Toronto",
  "Torquay",
  "Torquay",
  "Tottenham",
  "Toukley",
  "Townsville",
  "Towradgi",
  "Trafalgar",
  "Traralgon",
  "Traralgon South",
  "Trentham",
  "Trinity Beach",
  "Truganina",
  "Trunkey",
  "Tuggerah",
  "Tuggeranong",
  "Tugun",
  "Tullamarine",
  "Tully",
  "Tumut",
  "Tuncurry",
  "Tunnack",
  "Turners Beach",
  "Turramurra",
  "Tweed Heads",
  "Two Rocks",
  "Two Wells",
  "Tyabb",
  "Tyalgum",
  "Tynong",
  "Uki",
  "Ulladulla",
  "Ulmarra",
  "Ultimo",
  "Ulverstone",
  "Umina",
  "Unanderra",
  "Underwood",
  "Unley",
  "Upper Brookfield",
  "Upper Burringbar",
  "Upper Caboolture",
  "Upper Coomera",
  "Upwey",
  "Uraidla",
  "Urangan",
  "Valla Beach",
  "Valley Heights",
  "Vaucluse",
  "Venus Bay",
  "Verdun",
  "Vermont",
  "Victor Harbor",
  "Victoria Park",
  "Victoria Point",
  "Villawood",
  "Vineyard",
  "Virginia",
  "Virginia",
  "Waaia",
  "Wacol",
  "Wagga Wagga",
  "Wahgunyah",
  "Wahroonga",
  "Waikerie",
  "Waitara",
  "Walgett",
  "Walhalla",
  "Wallacia",
  "Wallan",
  "Wallaroo",
  "Wallington",
  "Walliston",
  "Wallsend",
  "Walmer",
  "Wamberal",
  "Wamuran",
  "Wanbi",
  "Wandin North",
  "Wandoan",
  "Wangaratta",
  "Wangi Wangi",
  "Wanneroo",
  "Wantirna",
  "Wantirna South",
  "Waratah",
  "Warburton",
  "Warnbro",
  "Warnervale",
  "Warragul",
  "Warrandyte",
  "Warrane",
  "Warrawong",
  "Warren",
  "Warren Shire",
  "Warrigal",
  "Warrimoo",
  "Warrnambool",
  "Warwick",
  "Waterford",
  "Waterloo",
  "Waterloo",
  "Waterloo",
  "Waterloo Corner",
  "Watsonia",
  "Wattle Grove",
  "Wattle Grove",
  "Waubra",
  "Wauchope",
  "Waurn Ponds",
  "Waverley",
  "Waverton",
  "Wayville",
  "Wedderburn",
  "Wedderburn",
  "Weetah",
  "Weethalle",
  "Wellard",
  "Wellington",
  "Wellington Point",
  "Welshpool",
  "Wembley",
  "Wendouree",
  "Wentworth",
  "Wentworth Falls",
  "Wentworthville",
  "Werribee",
  "Werribee South",
  "West Burleigh",
  "West End",
  "West Hoxton",
  "West Pymble",
  "West Wyalong",
  "Westbrook",
  "Westfield",
  "Westmead",
  "Weston",
  "Weston Creek",
  "Wheelers Hill",
  "White Rock",
  "Whitfield",
  "Whittlesea",
  "Whyalla",
  "Wickham",
  "Wickham",
  "Wilberforce",
  "Willaston",
  "Willaura",
  "Williams",
  "Williamstown",
  "Williamstown",
  "Willow Grove",
  "Willow Vale",
  "Willunga",
  "Wilmot",
  "Wilson",
  "Wilton",
  "Wiluna",
  "Wimbledon",
  "Winchelsea",
  "Windang",
  "Windaroo",
  "Windellama",
  "Windermere Park",
  "Windsor",
  "Windsor",
  "Windsor",
  "Windsor",
  "Windsor Downs",
  "Wingham",
  "Winkleigh",
  "Wodonga",
  "Wollar",
  "Wollert",
  "Wollongbar",
  "Wollongong",
  "Womboota",
  "Won Wron",
  "Wondai",
  "Wonga Park",
  "Wongan Hills",
  "Wonthaggi",
  "Woodburn",
  "Woodend",
  "Woodford",
  "Woodford",
  "Woodgate",
  "Woodleigh",
  "Woodridge",
  "Woodside",
  "Woodstock",
  "Woodvale",
  "Woodville",
  "Woolamai",
  "Woolgoolga",
  "Woolloomooloo",
  "Woolooware",
  "Wooloweyah",
  "Woolwich",
  "Woombah",
  "Woombye",
  "Woonona",
  "Woori Yallock",
  "Woorim",
  "Wooroolin",
  "Worongary",
  "Woronora",
  "Woy Woy",
  "Wulkuraka",
  "Wyalkatchem",
  "Wyalong",
  "Wyee",
  "Wyndham",
  "Wynnum",
  "Wynyard",
  "Wyong",
  "Wyongah",
  "Wyreema",
  "Yaamba",
  "Yackandandah",
  "Yallingup",
  "Yallourn",
  "Yallourn North",
  "Yamba",
  "Yanchep",
  "Yandina",
  "Yangan",
  "Yankalilla",
  "Yapeen",
  "Yaroomba",
  "Yarpturk",
  "Yarra Glen",
  "Yarra Junction",
  "Yarragon",
  "Yarram",
  "Yarraman",
  "Yarrambat",
  "Yarraville",
  "Yarrawarrah",
  "Yass",
  "Yatala",
  "Yea",
  "Yellow Rock",
  "Yenda",
  "Yeoval",
  "Yeppoon",
  "Yerrinbool",
  "Yinnar",
  "Yolla",
  "York",
  "Yorkeys Knob",
  "Young",
  "Yowie Bay",
  "Zeehan",
  "Addis Ababa",
  "Harrar",
  "Bonga",
  "Adama",
  "Dire Dawa",
  "Awassa"
];
